[project]
<<<<<<< HEAD
=======
[project]
name = "InvoiceMerger"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "chardet>=5.2.0",
    "numpy>=2.2.4",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "streamlit>=1.44.1",
    "xlrd>=2.0.1",
]
